### ISSUE TITLE
Implementation problem

### ISSUE THREAD

**Issue by ghost** [v420v/ibu#1]
Please run ibu and fix the problem.

**Comment by v420v** [comment]
Do you mean `ibuc` ?

**Comment by ghost** [comment]
Yes dear friend, when I compile it is facing many errors.
Please try it yourself.

**Comment by v420v** [comment]
![image](https://github.com/v420v/ibu/assets/106643445/6cbc8619-1180-4f26-ab5f-dacab490f351)

Could you share the specific errors you're encountering during compilation?

**Comment by v420v** [comment]
Ah, I misplaced the filename in the readme, sorry! Perhaps this is the cause of the error.

lib.s -> syscall-amd64.s

##How to build, compile programs written in Ibu

```
$ ./ibuc <filename>.ibu | as - -o <filename>.o
$ as -o lib/syscall-amd64.o lib/syscall-amd64.s
$ ld -o <filename> <filename>.o lib/syscall-amd64.o
```

**Comment by ghost** [comment]
Great, it's fixed now
thank you
